server:
  port: 8082

spring:
  application:
    name: manager_room
  data:
    mongodb:
      host: localhost
      port: 27017
      database: jarvis

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/